### ISSUE TITLE
Should not bump patch when minor or major versions are bumped using strategy=slow

### ISSUE THREAD

**Issue by grbsk** [semantic-gitlog/semantic-gitlog#8]
Hello!

I'm using `stragey="slow"` and am seeing some anomalies when you mix feat and fix, or a breaking change and any other non-breaking feat or fix.

If I start with a tag of v1 and add two commits:

```
commit abcd2

fix: bugfix 2
--------------

commit abcd1

fix: bugfix 2

doesn't matter what type of change, just that it's breaking

BREAKING CHANGE: had to introduce a breaking change to fix the bug
```

This will result in it generating a new version of 2.0.1, where I would expect 2.0.0

A similar issue happens when I mix feat and fix, again assuming a previous tag of 1.0.0:

```
commit abcd2

fix: bugfix 2
--------------

commit abcd1

feat: new feature 1
```

This results with version 1.1.1, where I would have expected 1.1.0.

My expectation with SemVer + Convetional Commit is that if you have a feat AND fix, minor is bumped and patch reset to 0. When a breaking change occurs, regardless of any additional feat or fix, major is bumped and minor as well as patch are reset to 0.

**Comment by ococl** [comment]
I did [some testing](https://github.com/semantic-gitlog/semantic-gitlog/blob/master/src/test/java/team/yi/tools/VersionDeriverTests.java) and fixed the issue. Is it what you expect ?

**Comment by grbsk** [comment]
Yes, I think so. In essence, if the major or minor number is bumped, all version numbers after the bumped segment should be reset to 0 and I think your tests demonstrate that in your fix. Thanks!

**Comment by ococl** [comment]
Thanks! I'll release a new version later.
