### ISSUE TITLE
Some commits ignored when multiple tags are associated with a single commit

### ISSUE THREAD

**Issue by s4heid** [semantic-gitlog/semantic-gitlog#9]
### Description

Given the scenario that a project follows semantic versioning when creating a new release tag on a commit. Additional, commits might be tagged with non-semver-conform tags (e.g. for ci purposes).

In that case semantic-gitlog is not able to parse the changelog properly.

### Example

Given the following versions:

* semantic-gitlog: `0.7.0`,
* gradle-semantic-gitlog: `5.3.17` with `build.gradle` config:

```Groovy
changelog {
    toRef = 'HEAD'
    isUnstable = true
    strategy = 'slow'

    jsonFile = file("${project.rootDir}/CHANGELOG.json")
    fileSets = [
            {
                // uses the default config from the docs:
                // https://semantic-gitlog.github.io/semantic-gitlog/#/en-us/with-gradle?id=_2-place-template
                template = file("${project.rootDir}/gradle/gitlog/CHANGELOG.mustache")
                target = file("${project.rootDir}/CHANGELOG.md")
            }
    ]
}
```

Below git history

```console
* 08caa11  (HEAD -> master) fix: test commit
* 33c0ba8  (tag: 0.3.0) refactor: fix several things
* b867a64  feat(gradle): add commit linter
* ddd02d9  (tag: 0.2.0, origin/master) feat: introduce new hooks api
* 2dbfd0f  style: solve static code checks
* a2cab2d  (tag: ms/0.1.0, tag: 0.1.0, origin/release, origin/0.x, release) release: 0.1.0
* 53b4d5e  chore: add script for publishing releases
* 4249910  feat: add changelog plugin
```

generate the following `CHANGELOG.md`:

```
# Changelog

## 0.3.1 (Unreleased, 2021-02-02)

### Bug Fixes

- test commit (08caa11)


## 0.3.0 (2021-02-01)

### Features

- **gradle**: add commit linter (b867a64)

### Code Refactoring

- fix several things (33c0ba8)


## 0.2.0 (2021-01-29)

### Style

- solve static code checks (2dbfd0f)

### Features

- introduce new hooks api (ddd02d90)

```

As you can see, it completely misses the commits `4249910` and `53b4d5e` from release `0.1.0`.

### Expected Behavior

The tool should not fail to parse the changelog. Instead, it should expect a single tag that is conform to semantic versioning. Other tags which are not conform should not be considered. At least there should be a way to make this configurable.

/cc @pk-work

**Comment by ococl** [comment]
Thanks for your contribution, I will evaluate it.

It will take a little longer, it's too busy recently.

**Comment by s4heid** [comment]
Hi @ymind, I hope you're doing good. I just wanted to friendly ask if you'll be able to look at the proposal in the near future?

**Comment by pk-work** [comment]
Hi @ymind, do you see any chance to release a new version with this patch within the next month?
